#!/usr/bin/env python3

# NOTE:
# This file is forked from singularity 2.2's "cli.py".  I have left the
# copyright notice below untouched; this file remains under the same license.
# - Brian Bockelman

'''

bootstrap.py: python helper for Singularity command line tool

Copyright (c) 2016, Vanessa Sochat. All rights reserved.

"Singularity" Copyright (c) 2016, The Regents of the University of California,
through Lawrence Berkeley National Laboratory (subject to receipt of any
required approvals from the U.S. Dept. of Energy).  All rights reserved.

This software is licensed under a customized 3-clause BSD license.  Please
consult LICENSE file distributed with the sources of this project regarding
your rights to use or distribute this software.

NOTICE.  This Software was developed under funding from the U.S. Department of
Energy and the U.S. Government consequently retains certain rights. As such,
the U.S. Government has been granted for itself and others acting on its
behalf a paid-up, nonexclusive, irrevocable, worldwide license in the Software
to reproduce, distribute copies to the public, prepare derivative works, and
perform publicly and display publicly, and to permit other to do so.


'''

import sys
import dockerhub
import docker
import argparse
import os
import errno
import fnmatch
import urllib.request, urllib.error, urllib.parse
import traceback

def main():
    parser = argparse.ArgumentParser(description="Bootstrap Docker images for Singularity containers deployed to CVMFS")

    # Name of the docker image, required
    parser.add_argument("--docker",
                        dest='docker',
                        help="name of Docker image to bootstrap, in format library/ubuntu:latest",
                        type=str,
                        default=None)

    # Name of the docker image url, required
    parser.add_argument("--images-url",
                        dest='filelist',
                        help="URL to download a list of Docker images from",
                        type=str,
                        default=None)

    # Name of the docker image file, required
    parser.add_argument("--images-file",
                        dest='filelist_path',
                        help="Local file path to a list of Docker images",
                        type=str,
                        default=None)

    # root file system of singularity image
    parser.add_argument("--rootfs",
                        dest='rootfs',
                        help="the path for the root filesystem to extract to",
                        type=str,
                        default=None)

    # Socket to local docker engine
    parser.add_argument("--docker-socket",
                        dest='socket',
                        help="connect to specified docker socket rather than using docker.from_env()",
                        type=str,
                        default=None)

    # Docker registry (default is registry-1.docker.io)
    parser.add_argument("--registry",
                        dest='registry',
                        help="the registry path to use, to replace registry-1.docker.io",
                        type=str,
                        default=None)

    # Flag to indicate a token is not required
    parser.add_argument("--no-token",
                        dest='notoken',
                        action="store_true",
                        help="Indicate that auth is not required",
                        default=False)


    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        sys.exit(0)

    # Does the registry require a token?
    doauth = not args.notoken

    # Do we have a docker image specified?
    if not args.docker and not (args.filelist or args.filelist_path):
        print("No docker image or file list specified..", file=sys.stderr)
        return 1

    currentImages = []
    if args.docker:
        image = args.docker
        return publish_image(image, args.registry, doauth, args.socket)
    else:
        final_retval = 0
        if args.filelist:
            fp = urllib.request.urlopen(args.filelist).read().decode().split('\n')
        else: 
            if args.filelist_path:
                fp = open(args.filelist_path, "r").read().split('\n')
        for image in fp:
            image = image.strip()
            if image.startswith("#") or not image:
                continue
            registry, namespace, repo_name, repo_tag = parse_image(image)
            print("Working on image: {}".format(image))

            if '*' in repo_tag: # Treat wildcards as a glob
                try:
                    tag_names = get_tags(namespace, repo_name, registry=registry, auth=doauth)
                except Exception as ex:
                    image = '%s/%s/%s' % (registry, namespace, repo_name)
                    print("Failed to get tags for image: {}".format(image))
                    traceback.print_exc()
                    print(ex)
                    continue
                repo_tag = fnmatch.filter(tag_names, repo_tag)
            else:
                repo_tag = [repo_tag]

            for tag in repo_tag:
                image = '%s/%s/%s:%s' % (registry, namespace, repo_name, tag)
                currentImages.append(image)
                retval = 1
                try:
                    retval = publish_image(image, registry, doauth, args.socket)
                except Exception as ex:
                    #print("Failed to publish image: {}".format(image))
                    print("Failed to verify image: {}".format(image))
                    traceback.print_exc()

                if retval:
                    final_retval = retval
        print("All requested images have been attempted; final return code: %d" % final_retval)
        return final_retval


def get_tags(username, repo, registry=None, auth=None):
    if registry != "registry.hub.docker.com":
        if "://" not in registry:
            registry = "https://%s" % registry
        hub = dockerhub.DockerHub(url=registry)
    else:
        hub = dockerhub.DockerHub()
    tag_names = []
    for tag in hub.tags(username, repo):
        tag_names.append(tag['name'])
    return tag_names

def parse_image(image):
    """
    Parse an image string into image components, setting appropriate defaults.
    Returns a tuple of (registry, namespace, repo_name, repo_tag).
    """

    # INPUT PARSING -------------------------------------------
    # Parse registry, image name, repo name, and namespace
    # Support different formats:
    # opensciencegrid/osgvo-julia:latest
    # opensciencegrid/osgvo-ants
    # openjdk:8
    # containers.ligo.org/lscsoft/lalsuite/lalsuite-v6.53:stretch
    registry = "registry.hub.docker.com"
    # First split the docker image name by /
    split_image = image.split('/')

    # If there are two parts, we have namespace with repo (and maybe tab)
    if len(split_image) == 2:
        namespace = split_image[0]
        image = split_image[1]
    elif len(split_image) > 2:
        # We have a custom registry
        registry = split_image[0]
        print("Custom registry:", registry)
        namespace = split_image[1]
        image = "/".join(split_image[2:])
    # Otherwise, we must be using library namespace
    else:
        namespace = "library"
        image = split_image[0]

    # Now split the docker image name by :
    image = image.split(':')
    if len(image) == 2:
        repo_name = image[0]
        repo_tag = image[1]

    # Otherwise, assume latest of an image
    else:
        repo_name = image[0]
        repo_tag = "latest"

    return registry, namespace, repo_name, repo_tag

def publish_image(image, registry, doauth, socket=None):

    # Tell the user the namespace, repo name and tag
    registry, namespace, repo_name, repo_tag = parse_image(image)
    #print("Docker image to publish: %s/%s/%s:%s" % (registry, namespace, repo_name, repo_tag))
    print("Docker image to verify: %s/%s/%s:%s" % (registry, namespace, repo_name, repo_tag))


# IMAGE METADATA -------------------------------------------
# Use Docker Registry API (version 2.0) to get images ids, manifest

    # Get an image manifest - has image ids to parse, and will be
    # used later to get Cmd
    # Prepend "https://" to the registry
    if "://" not in registry:
        registry = "https://%s" % registry
    hub = dockerhub.DockerHub(url=registry)
    try: 
        hub.manifest(namespace, repo_name, repo_tag)
        print(repo_name + ":" + repo_tag + " manifest found")
        return 0
    except Exception as ex:
        print(repo_name + ":" + repo_tag + " manifest not found")
        return 1


if __name__ == '__main__':
    sys.exit(main())
